# Departamentos de Walmart US
TOYS_VIDEOGAMES            = c('MEDIA_AND_GAMING', 'PLAYERS_AND_ELECTRONICS','TOYS')
IMPROVEMENT_PATIO          = c('HORTICULTURE_AND_ACCESS', 'LAWN_AND_GARDEN', 'PAINT_AND_ACCESSORIES')

ELECTRONICS_OFFICE         = c('ACCESSORIES', 'ELECTRONICS', 'HARDWARE', 'OFFICE_SUPPLIES', 
                               'WIRELESS', 'CAMERAS_AND_SUPPLIES')
MOVIES_MUSIC_BOOKS         = c('BOOKS_AND_MAGAZINES')

HOME_FORNITURE_APPLIANCES  = c('BEDDING', 'CONCEPT_STORES', 'COOK_AND_DINE', 'FURNITURE',
                               'HOME_DECOR', 'HOME_MANAGEMENT', 'LARGE_HOUSEHOLD_GOODS')


CLOTHING                   = c('BOYS_WEAR', 'BRAS_&_SHAPEWEAR', 'GIRLS_WEAR_4_6X_AND_7_14', 
                               'JEWELRY_AND_SUNGLASSES', 'LADIES_SOCKS', 'LADIESWEAR', 'MENSWEAR', 'MENS_WEAR',
                               'PLUS_AND_MATERNITY', 'SHEER_HOSIERY', 'SLEEPWEAR_FOUNDATIONS')
SHOES_ACCESSORIES          = c('JEWELRY_AND_SUNGLASSES','SHOES')
BABY_TODDLER              = c('INFANT_CONSUMABLE_HARDLINES', 'INFANT_APPAREL')

FOOD                      = c('BAKERY', 'CANDY_TOBACCO_COOKIES', 'COMM_BREAD', 'DAIRY', 'DSD_GROCERY', 
                              'FROZEN_FOODS', 'GROCERY_DRY_GOODS', 'MEAT__FRESH_&_FROZEN',
                              'PRE_PACKED_DELI','PRODUCE', 'SEAFOOD', 'SERVICE_DELI')
HOUSEHOLD                  = c('HOUSEHOLD_CHEMICALS_SUPP', 'HOUSEHOLD_PAPER_GOODS')
PHARMA_OPTICAL             = c('PHARMACY_OTC', 'PHARMACY_RX','OPTICAL__FRAMES', 'OPTICAL__LENSES')
BEAUTY                     = c('HEALTH_AND_BEAUTY_AIDS','BEAUTY','PERSONAL_CARE')
SPORTS_FIT_OUTDOORS        = c('SPORTING_GOODS', 'SWIMWEAR_OUTERWEAR')
AUTO_TIRES_INDUSTRIAL      = c('AUTOMOTIVE')
PHOTO_PERSONALIZED        = c('1_HR_PHOTO')
ART_CRAFT_PARTY            = c('CELEBRATION', 'FABRICS_AND_CRAFTS', 'SEASONAL')